# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

## YAML Template.
---
compas:
  scl:
    # XsdPath currently is a reference to a XSD on the classpath, searched from the root.
    # ContextPath is the package where the ObjectFactory class can be found, mostly generated there.
    schemas:
      - xsdPath: "xsd/SCL2003/SCL.xsd"
        namespace: "http://www.iec.ch/61850/2003/SCL"
        contextPath: "org.lfenergy.compas.scl2003.model"
      - xsdPath: "xsd/SCL_CoMPAS.xsd"
        namespace: "https://www.lfenergy.org/compas/v1"
        contextPath: "org.lfenergy.compas.scl.extensions.model"
